-- KC PROJECT LEADS — migration 0002: brands master + field-lead form fields
-- Re-runnable (idempotent upsert). Run AFTER 0001_init.sql, any time you update the brand list.

create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  brand text unique not null,
  sales_poc text,
  onboarding_poc text,
  category text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.brands add column if not exists category text;   -- safe if table pre-existed
drop trigger if exists trg_brands_updated on public.brands;
create trigger trg_brands_updated before update on public.brands
  for each row execute function public.set_updated_at();

alter table public.brands enable row level security;
drop policy if exists "anon_all" on public.brands;
create policy "anon_all" on public.brands for all to anon, authenticated using (true) with check (true);
grant all on public.brands to anon, authenticated;

-- new field-lead column
alter table public.field_leads add column if not exists known_contact text;   -- architect/contractor phone

-- seed / refresh the brand master list (brand, sales_poc, onboarding_poc, category)
insert into public.brands (brand, sales_poc, onboarding_poc, category) values
('3Dclay-Art Station By Riya Patel','Renu','Keshav','Decor'),
('Action Tesa','Roshan','Neeraj','Wood'),
('Adhvik Décor','Garima','Rahul','Furnishing'),
('Aflux India Lighting Expert Since 2009','Roshan','Neeraj','Electrical'),
('AGL Tiles World','Kanishk',null,'Tile'),
('Aica','Roshan','Neeraj','Wood'),
('Alex','Renu','Keshav','ACP'),
('Artline Creation(Vikas Enterprises)','Rahul & Vaishali','Rahul','Decor'),
('Artociti Canvas Private Limited','Suhana','Hemam','Decor-Wall Art & Wall Painting'),
('Atcraft Creations Private Limited','Renu','Keshav','Hardware'),
('Athmer','Soham','Neeraj','Hardware (Sealants)'),
('Aurelia Knots','Garima','Rahul','Decor'),
('Beton Gold','Soham','Rishiraj Gill','Wood'),
('Bilawat Marbles','Kanishk','Neeraj','Stone'),
('Black Cobra','Renu','Keshav','polymercomposite panels, louvers, jali and screens, wpc board, ply and board, laminates'),
('Blue Knot Home Pvt Ltd','Vaishali','Rahul','Carpet'),
('Bodaq','Renu','Mahesh','Interior Finishes (Film)'),
('Casagres Tile (Motto)','Simran Pandita','Rishiraj Gill','Tiles'),
('Century','Dhiraj','Aastha','Wood'),
('CrossBond','Roshan','Neeraj','Wood'),
('CrudeFree','Harsh','Keshav','Eco-friendly Surfaces / Finishes'),
('DEE PEARLS','Renu','Keshav','Stone'),
('Dkan',null,'Neeraj','Hardware'),
('Door Base','Shiv','Hassan','Hardware'),
('DRV Overseas Export','Roshan','Mahesh','Wood'),
('Duro','Renu','Rahul','Wood'),
('E3',null,'Mahesh','Wood'),
('Eclisse',null,null,'Hardware (Door Accessories)'),
('Elegancia','Kanishk','Neeraj','Furnishing / Wallpaper'),
('Everite Agencies Pvt Ltd','Nikhil','Rishiraj','Hardware'),
('Fensa Window','Shiv','Hassan','Doors & Windows'),
('Frits Jurgen','Soham','Neeraj','Hardware (Hinges)'),
('Glamstone','Renu','Keshav','Stone'),
('Gold Plus Float Glass','Roshan','Neeraj','Glass'),
('Greenlam','Roshan','Neeraj','Wood(Laminate)'),
('Haique Esprit Stone Limited','Ayush','Abhishek','Stone'),
('Handlier','Renu','Keshav','Hardware'),
('Hawa',null,null,'Hardware (Sliding Systems)'),
('Incor','Renu','Aastha','Doors & Windows'),
('Indian Granite','Shiv','Hassan','Stone'),
('Karnav','Renu','Keshav','Wood(Veneer)'),
('Kei Industries','Kanishk','Neeraj','Electrical - Wires & Cables'),
('Kohinoor Woollen Carpet','Astha & Vaishali','Astha','Carpets'),
('Kopek Kitchens','Kanishk','Neeraj','Modular Kitchens / Furniture'),
('Livin Blinds','Shiv','Hassan','Blinds'),
('Luxture surface Coating Pvt Ltd','Kanishk','Neeraj','Paint & Coats'),
('Madhusudan Marble Pvt Ltd','Ayush','Keshav','Stone'),
('Mantion',null,'Neeraj','Hardware (Sliders & Runners)'),
('Mark Decor','Pratibha','Astha','Polymer Composite'),
('Metro Arte Ceramica','Simran Pandita','Rishiraj','Tiles'),
('NewMika','Roshan','Neeraj','Wood(Laminate)'),
('Mkasa Decor(Wooden Louver)','Roshan','Neeraj','Louvers'),
('Moldo Sports, Bizzar','Renu','Keshav','All'),
('Nascosto',null,null,'Hardware (Hinges)'),
('Norisys Technology Private Limited','Pihu','Ajay','Electrical - Switches & Sockets'),
('Nuzen','Roshan','Hassan','Home Appliances'),
('Oasis','Renu','Keshav','Hardware'),
('P.K Lighting (Scoot)','Suhana',null,'Electrical'),
('Pavit Inspired Mind Capes','Simran pandita','Rishiraj','Tile'),
('Pioneer','Renu','Keshav','Hardware'),
('Prarthana Wootlex Pvt. Ltd.','Shiv','Hassan','Fabric (Natural)'),
('Response Fabrics','Renu','Keshav','Furnishing'),
('Sachi Art Design','Garima','Rishiraj Gill','Art & Decor'),
('Saf India Galss','Shiv',null,'Doors & Windows'),
('Simonswerk',null,null,'Hardware (Hinges)'),
('Specta Quartz Surfaces','Shiv','Hassan','Stone'),
('Sris Ma Fils Premium Door Handles & Locks','Pihu','Ajay','Hardware'),
('Surajwood Products Pvt Ltd','Renu','Keshav','Polymer Composite'),
('SURFEX FUTURE OF SURFACES',null,null,'CBC Board'),
('The Art Super Craft','Suhana',null,'Decor-Wall Art & Wall Painting'),
('The Tile World','Renu','Keshav','Tile(Terracota)'),
('TOYAMA FLOORS INDIA','Soham','Rahul','Wood (Flooring) & Polymer Composite'),
('Twigs Direct','Soham','Rahul','Furniture'),
('UDC Homes','Renu','Rahul','Wallpaper & Decor'),
('Veneto Wardrobes & More','Shiv','Hassan','Doors & Windows'),
('Vetra Furnitures','Renu','Keshav','Furniture'),
('Vikram Carpets(Vikas Enterprises)','Vaishali','Rahul','Carpets'),
('Winvista','Kanishk','Neeraj','Doors & Windows'),
('Wood Walk','Soham','Rahul','Wood'),
('Wudlay','Garima','Neeraj','Wood'),
('Yen Door Closer','Daksh','Astha','Hardware'),
('Amit Marbles','Ayush','Abhishek',null),
('Camrola Quartz','Soham','Rahul',null),
('Datti Ram Marbles','Soham','Rahul',null),
('Essgeeleather Goods','Suhana','Hemam',null),
('JSB','Soham',null,null),
('Krishna Stonex','Soham','Rahul',null),
('Mahayco','Soham','Neeraj',null),
('O.P. Marbles','Soham','Rahul',null),
('RKS Marbles','Soham','Rahul',null),
('Shubh Gem Stone','Soham','Rahul',null),
('Square Root','Kanishk','Neeraj',null),
('Vaishno Light','Suhana',null,null),
('Vasudev','Ayush','Rishiraj',null),
('Vinay Marbles','Soham','Rahul',null),
('Square 1','Daksh','Astha','Hardware'),
('A-Class Marble','Renu','Keshav','Stone'),
('Wonder Alu Board (G.M Alloys Private Limited)','Daksh','Astha',null),
('JK Stone','Soham',null,null),
('Althiacraft','Roshan',null,null),
('Tata Pravesh','Roshan',null,null),
('Aristo','Roshan',null,null),
('OTS Impex','Roshan',null,null),
('AEGON','Harsh',null,null),
('TACO','Harsh',null,null),
('Latrove',null,null,null),
('Ritu bricks','Harsh',null,null),
('NCJ','Shiv',null,null),
('DORPICK','Harsh',null,null),
('Simpolo Tiles & Bathware','Renu',null,null),
('Dev Raj Ram Raj',null,null,null),
('Jindal Marmo Impex Pvt. Ltd.',null,null,null),
('Tile Gallery',null,null,null),
('Simta Astrix',null,null,null),
('Phantom Blinds',null,null,null),
('RK Metal Wood & Crafts',null,null,null),
('QIBO','Renu','Keshav',null),
('Billion ply','Renu','Keshav',null),
('Square Feet',null,null,null),
('RMS Stonex',null,null,null),
('Vidhyanand Marble',null,null,null),
('Saptgiri',null,null,null),
('Manish Marbles',null,null,null),
('Woodys By Mille',null,null,null),
('JBMR Furnitech',null,null,null),
('Sarvesh Euroline',null,null,null),
('EuropaFenestra',null,null,null),
('LegnosoArt',null,null,null),
('Nayur Paints','Shiv',null,null),
('Nimco',null,null,null),
('S-GRIP',null,null,null),
('Rigwell',null,null,null),
('3R Joints & seal',null,null,null),
('Modutech','Shiv',null,null),
('Polo',null,null,null),
('Adona Woods',null,null,null),
('OptionsUnlimited',null,null,null),
('ELVORA SEATING',null,null,null),
('The Art Warehouse',null,null,null),
('Agni',null,null,null),
('Mikasa Laminates',null,null,null),
('VG Sales - Bizzare',null,null,null),
('DARS Interiorwood Design',null,null,null)
on conflict (brand) do update
  set sales_poc = excluded.sales_poc,
      onboarding_poc = excluded.onboarding_poc,
      category = excluded.category;
