-- KC PROJECT LEADS — migration 0002: brands master + field-lead form fields
-- Run AFTER 0001_init.sql (order doesn't matter vs seed.sql). Idempotent.

create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  brand text unique not null,
  sales_poc text,
  onboarding_poc text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
drop trigger if exists trg_brands_updated on public.brands;
create trigger trg_brands_updated before update on public.brands
  for each row execute function public.set_updated_at();

alter table public.brands enable row level security;
drop policy if exists "anon_all" on public.brands;
create policy "anon_all" on public.brands for all to anon, authenticated using (true) with check (true);
grant all on public.brands to anon, authenticated;

-- new field-lead columns
alter table public.field_leads add column if not exists known_contact text;   -- architect/contractor phone

-- seed the brand master list (from Onboarding Tracker). Safe to re-run.
insert into public.brands (brand, sales_poc, onboarding_poc) values
('3Dclay-Art Station By Riya Patel','Renu','Keshav'),
('Action Tesa','Roshan','Neeraj'),
('Adhvik Décor','Garima','Rahul'),
('Aflux India Lighting Expert Since 2009','Roshan','Neeraj'),
('AGL Tiles World','Kanishk',null),
('Aica','Roshan','Neeraj'),
('Alex','Renu','Keshav'),
('Artline Creation(Vikas Enterprises)','Rahul & Vaishali','Rahul'),
('Artociti Canvas Private Limited','Suhana','Hemam'),
('Atcraft Creations Private Limited','Renu','Keshav'),
('Athmer','Soham','Neeraj'),
('Aurelia Knots','Garima','Rahul'),
('Beton Gold','Soham','Rishiraj Gill'),
('Bilawat Marbles','Kanishk','Neeraj'),
('Black Cobra','Renu','Keshav'),
('Blue Knot Home Pvt Ltd','Vaishali','Rahul'),
('Bodaq','Renu','Mahesh'),
('Casagres Tile (Motto)','Simran Pandita','Rishiraj Gill'),
('Century','Dhiraj','Aastha'),
('CrossBond','Roshan','Neeraj'),
('CrudeFree','Harsh','Keshav'),
('DEE PEARLS','Renu','Keshav'),
('Dkan',null,'Neeraj'),
('Door Base','Shiv','Hassan'),
('DRV Overseas Export','Roshan','Mahesh'),
('Duro','Renu','Rahul'),
('E3',null,'Mahesh'),
('Eclisse',null,null),
('Elegancia','Kanishk','Neeraj'),
('Everite Agencies Pvt Ltd','Nikhil','Rishiraj'),
('Fensa Window','Shiv','Hassan'),
('Frits Jurgen','Soham','Neeraj'),
('Glamstone','Renu','Keshav'),
('Gold Plus Float Glass','Roshan','Neeraj'),
('Greenlam','Roshan','Neeraj'),
('Haique Esprit Stone Limited','Ayush','Abhishek'),
('Handlier','Renu','Keshav'),
('Hawa',null,null),
('Incor','Renu','Aastha'),
('Indian Granite','Shiv','Hassan'),
('Karnav','Renu','Keshav'),
('Kei Industries','Kanishk','Neeraj'),
('Kohinoor Woollen Carpet','Astha & Vaishali','Astha'),
('Kopek Kitchens','Kanishk','Neeraj'),
('Livin Blinds','Shiv','Hassan'),
('Luxture surface Coating Pvt Ltd','Kanishk','Neeraj'),
('Madhusudan Marble Pvt Ltd','Ayush','Keshav'),
('Mantion',null,'Neeraj'),
('Mark Decor','Pratibha','Astha'),
('Metro Arte Ceramica','Simran Pandita','Rishiraj'),
('NewMika','Roshan','Neeraj'),
('Mkasa Decor(Wooden Louver)','Roshan','Neeraj'),
('Moldo Sports, Bizzar','Renu','Keshav'),
('Nascosto',null,null),
('Norisys Technology Private Limited','Pihu','Ajay'),
('Nuzen','Roshan','Hassan'),
('Oasis','Renu','Keshav'),
('P.K Lighting (Scoot)','Suhana',null),
('Pavit Inspired Mind Capes','Simran pandita','Rishiraj'),
('Pioneer','Renu','Keshav'),
('Prarthana Wootlex Pvt. Ltd.','Shiv','Hassan'),
('Response Fabrics','Renu','Keshav'),
('Sachi Art Design','Garima','Rishiraj Gill'),
('Saf India Galss','Shiv',null),
('Simonswerk',null,null),
('Specta Quartz Surfaces','Shiv','Hassan'),
('Sris Ma Fils Premium Door Handles & Locks','Pihu','Ajay'),
('Surajwood Products Pvt Ltd','Renu','Keshav'),
('SURFEX FUTURE OF SURFACES',null,null),
('The Art Super Craft','Suhana',null),
('The Tile World','Renu','Keshav'),
('TOYAMA FLOORS INDIA','Soham','Rahul'),
('Twigs Direct','Soham','Rahul'),
('UDC Homes','Renu','Rahul'),
('Veneto Wardrobes & More','Shiv','Hassan'),
('Vetra Furnitures','Renu','Keshav'),
('Vikram Carpets(Vikas Enterprises)','Vaishali','Rahul'),
('Winvista','Kanishk','Neeraj'),
('Wood Walk','Soham','Rahul'),
('Wudlay','Garima','Neeraj'),
('Yen Door Closer','Daksh','Astha'),
('Amit Marbles','Ayush','Abhishek'),
('Camrola Quartz','Soham','Rahul'),
('Datti Ram Marbles','Soham','Rahul'),
('Essgeeleather Goods','Suhana','Hemam'),
('JSB','Soham',null),
('Krishna Stonex','Soham','Rahul'),
('Mahayco','Soham','Neeraj'),
('O.P. Marbles','Soham','Rahul'),
('RKS Marbles','Soham','Rahul'),
('Shubh Gem Stone','Soham','Rahul'),
('Square Root','Kanishk','Neeraj'),
('Vaishno Light','Suhana',null),
('Vasudev','Ayush','Rishiraj'),
('Vinay Marbles','Soham','Rahul'),
('Square 1','Daksh','Astha'),
('A-Class Marble','Renu','Keshav'),
('Wonder Alu Board (G.M Alloys Private Limited)','Daksh','Astha'),
('JK Stone','Soham',null),
('Althiacraft','Roshan',null),
('Tata Pravesh','Roshan',null),
('Aristo','Roshan',null),
('OTS Impex','Roshan',null),
('AEGON','Harsh',null),
('TACO','Harsh',null),
('Latrove',null,null),
('Ritu bricks','Harsh',null),
('NCJ','Shiv',null),
('DORPICK','Harsh',null),
('Simpolo Tiles & Bathware','Renu',null),
('Dev Raj Ram Raj',null,null),
('Jindal Marmo Impex Pvt. Ltd.',null,null),
('Tile Gallery',null,null),
('Simta Astrix',null,null),
('Phantom Blinds',null,null),
('RK Metal Wood & Crafts',null,null),
('QIBO','Renu','Keshav'),
('Billion ply','Renu','Keshav'),
('Square Feet',null,null),
('RMS Stonex',null,null),
('Vidhyanand Marble',null,null),
('Saptgiri',null,null),
('Manish Marbles',null,null),
('Woodys By Mille',null,null),
('JBMR Furnitech',null,null),
('Sarvesh Euroline',null,null),
('EuropaFenestra',null,null),
('LegnosoArt',null,null),
('Nayur Paints','Shiv',null),
('Nimco',null,null),
('S-GRIP',null,null),
('Rigwell',null,null),
('3R Joints & seal',null,null),
('Modutech','Shiv',null),
('Polo',null,null),
('Adona Woods',null,null),
('OptionsUnlimited',null,null),
('ELVORA SEATING',null,null),
('The Art Warehouse',null,null),
('Agni',null,null),
('Mikasa Laminates',null,null),
('VG Sales - Bizzare',null,null),
('DARS Interiorwood Design',null,null)
on conflict (brand) do nothing;
