-- KC PROJECT LEADS — migration 0007: brand master (categories + SPOCs)
-- Populates the general brand master with Category + POCs, and rebuilds the
-- paid/onboarded routing master (paid_brands) from the KC Sales POC assignments.
-- A brand WITH a KC Sales POC is treated as onboarded -> opportunities route to that
-- SPOC. Brands without a POC route by category to a Category Team Lead.
-- Run AFTER 0001-0006. Idempotent (upserts by brand).

-- brands master needs category + POC columns
alter table public.brands add column if not exists category text;
alter table public.brands add column if not exists sales_poc text;
alter table public.brands add column if not exists onboarding_poc text;

-- Upsert the full brand list (brand | category | sales_poc | onboarding_poc)
insert into public.brands (brand, category, sales_poc, onboarding_poc) values
('3Dclay-Art Station By Riya Patel','Decor','Renu','Keshav'),
('Action Tesa','Wood','Roshan','Neeraj'),
('Adhvik Décor','Furnishing','Garima','Rahul'),
('Aflux India Lighting Expert Since 2009','Electrical','Roshan','Neeraj'),
('AGL Tiles World','Tile','Kanishk',null),
('Aica','Wood','Roshan','Neeraj'),
('Alex','ACP','Renu','Keshav'),
('Artline Creation(Vikas Enterprises)','Decor','Rahul & Vaishali','Rahul'),
('Artociti Canvas Private Limited','Decor-Wall Art & Wall Painting','Suhana','Hemam'),
('Atcraft Creations Private Limited','Hardware','Renu','Keshav'),
('Athmer','Hardware (Sealants)','Soham','Neeraj'),
('Aurelia Knots','Decor','Garima','Rahul'),
('Beton Gold','Wood','Soham','Rishiraj Gill'),
('Bilawat Marbles','Stone','Kanishk','Neeraj'),
('Black Cobra','polymercomposite panels louvers jali and screens wpc board ply and board laminates','Renu','Keshav'),
('Blue Knot Home Pvt Ltd','Carpet','Vaishali','Rahul'),
('Bodaq','Interior Finishes (Film)','Renu','Mahesh'),
('Casagres Tile (Motto)','Tiles','Simran Pandita','Rishiraj Gill'),
('Century','Wood','Dhiraj','Aastha'),
('CrossBond','Wood','Roshan','Neeraj'),
('CrudeFree','Eco-friendly Surfaces / Finishes','Harsh','Keshav'),
('DEE PEARLS','Stone','Renu','Keshav'),
('Dkan','Hardware',null,'Neeraj'),
('Door Base','Hardware','Shiv','Hassan'),
('DRV Overseas Export','Wood','Roshan','Mahesh'),
('Duro','Wood','Renu','Rahul'),
('E3','Wood',null,'Mahesh'),
('Eclisse','Hardware (Door Accessories)',null,null),
('Elegancia','Furnishing / Wallpaper','Kanishk','Neeraj'),
('Everite Agencies Pvt Ltd','Hardware','Nikhil','Rishiraj'),
('Fensa Window','Doors & Windows','Shiv','Hassan'),
('Frits Jurgen','Hardware (Hinges)','Soham','Neeraj'),
('Glamstone','Stone','Renu','Keshav'),
('Gold Plus Float Glass','Glass','Roshan','Neeraj'),
('Greenlam','Wood(Laminate)','Roshan','Neeraj'),
('Haique Esprit Stone Limited','Stone','Ayush','Abhishek'),
('Handlier','Hardware','Renu','Keshav'),
('Hawa','Hardware (Sliding Systems)',null,null),
('Incor','Doors & Windows','Renu','Aastha'),
('Indian Granite','Stone','Shiv','Hassan'),
('Karnav','Wood(Veneer)','Renu','Keshav'),
('Kei Industries','Electrical - Wires & Cables','Kanishk','Neeraj'),
('Kohinoor Woollen Carpet','Carpets','Astha & Vaishali','Astha'),
('Kopek Kitchens','Modular Kitchens / Furniture','Kanishk','Neeraj'),
('Livin Blinds','Blinds','Shiv','Hassan'),
('Luxture surface Coating Pvt Ltd','Paint & Coats','Kanishk','Neeraj'),
('Madhusudan Marble Pvt Ltd','Stone','Ayush','Keshav'),
('Mantion','Hardware (Sliders & Runners)',null,'Neeraj'),
('Mark Decor','Polymer Composite','Pratibha','Astha'),
('Metro Arte Ceramica','Tiles','Simran Pandita','Rishiraj'),
('NewMika','Wood(Laminate)','Roshan','Neeraj'),
('Mkasa Decor(Wooden Louver)','Louvers','Roshan','Neeraj'),
('Moldo Sports, Bizzar','All','Renu','Keshav'),
('Nascosto','Hardware (Hinges)',null,null),
('Norisys Technology Private Limited','Electrical - Switches & Sockets','Pihu','Ajay'),
('Nuzen','Home Appliances','Roshan','Hassan'),
('Oasis','Hardware','Renu','Keshav'),
('P.K Lighting (Scoot)','Electrical','Suhana',null),
('Pavit Inspired Mind Capes','Tile','Simran pandita','Rishiraj'),
('Pioneer','Hardware','Renu','Keshav'),
('Prarthana Wootlex Pvt. Ltd.','Fabric (Natural)','Shiv','Hassan'),
('Response Fabrics','Furnishing','Renu','Keshav'),
('Sachi Art Design','Art & Decor','Garima','Rishiraj Gill'),
('Saf India Galss','Doors & Windows','Shiv',null),
('Simonswerk','Hardware (Hinges)',null,null),
('Specta Quartz Surfaces','Stone','Shiv','Hassan'),
('Sris Ma Fils Premium Door Handles & Locks','Hardware','Pihu','Ajay'),
('Surajwood Products Pvt Ltd','Polymer Composite','Renu','Keshav'),
('SURFEX FUTURE OF SURFACES','CBC Board',null,null),
('The Art Super Craft','Decor-Wall Art & Wall Painting','Suhana',null),
('The Tile World','Tile(Terracota)','Renu','Keshav'),
('TOYAMA FLOORS INDIA','Wood (Flooring) & Polymer Composite','Soham','Rahul'),
('Twigs Direct','Furniture','Soham','Rahul'),
('UDC Homes','Wallpaper & Decor','Renu','Rahul'),
('Veneto Wardrobes & More','Doors & Windows','Shiv','Hassan'),
('Vetra Furnitures','Furniture','Renu','Keshav'),
('Vikram Carpets(Vikas Enterprises)','Carpets','Vaishali','Rahul'),
('Winvista','Doors & Windows','Kanishk','Neeraj'),
('Wood Walk','Wood','Soham','Rahul'),
('Wudlay','Wood','Garima','Neeraj'),
('Yen Door Closer','Hardware','Daksh','Astha'),
('Amit Marbles',null,'Ayush','Abhishek'),
('Camrola Quartz',null,'Soham','Rahul'),
('Datti Ram Marbles',null,'Soham','Rahul'),
('Essgeeleather Goods',null,'Suhana','Hemam'),
('JSB',null,'Soham',null),
('Krishna Stonex',null,'Soham','Rahul'),
('Mahayco',null,'Soham','Neeraj'),
('O.P. Marbles',null,'Soham','Rahul'),
('RKS Marbles',null,'Soham','Rahul'),
('Shubh Gem Stone',null,'Soham','Rahul'),
('Square Root',null,'Kanishk','Neeraj'),
('Vaishno Light',null,'Suhana',null),
('Vasudev',null,'Ayush','Rishiraj'),
('Vinay Marbles',null,'Soham','Rahul'),
('Square 1','Hardware','Daksh','Astha'),
('A-Class Marble','Stone','Renu','Keshav'),
('Wonder Alu Board (G.M Alloys Private Limited)',null,'Daksh','Astha'),
('JK Stone',null,'Soham',null),
('Althiacraft',null,'Roshan',null),
('Tata Pravesh',null,'Roshan',null),
('Aristo',null,'Roshan',null),
('OTS Impex',null,'Roshan',null),
('AEGON',null,'Harsh',null),
('TACO',null,'Harsh',null),
('Latrove',null,null,null),
('Ritu bricks',null,'Harsh',null),
('NCJ',null,'Shiv',null),
('DORPICK',null,'Harsh',null),
('Simpolo Tiles & Bathware',null,'Renu',null),
('Dev Raj Ram Raj',null,null,null),
('Jindal Marmo Impex Pvt. Ltd.',null,null,null),
('Tile Gallery',null,null,null),
('Simta Astrix',null,null,null),
('Phantom Blinds',null,null,null),
('RK Metal Wood & Crafts',null,null,null),
('QIBO',null,'Renu','Keshav'),
('Billion ply',null,'Renu','Keshav'),
('Square Feet',null,null,null),
('RMS Stonex',null,null,null),
('Vidhyanand Marble',null,null,null),
('Saptgiri',null,null,null),
('Manish Marbles',null,null,null),
('Woodys By Mille',null,null,null),
('JBMR Furnitech',null,null,null),
('Sarvesh Euroline',null,null,null),
('EuropaFenestra',null,null,null),
('LegnosoArt',null,null,null),
('Nayur Paints',null,'Shiv',null),
('Nimco',null,null,null),
('S-GRIP',null,null,null),
('Rigwell',null,null,null),
('3R Joints & seal',null,null,null),
('Modutech',null,'Shiv',null),
('Polo',null,null,null),
('Adona Woods',null,null,null),
('OptionsUnlimited',null,null,null),
('ELVORA SEATING',null,null,null),
('The Art Warehouse',null,null,null),
('Agni',null,null,null),
('Mikasa Laminates',null,null,null),
('VG Sales - Bizzare',null,null,null),
('DARS Interiorwood Design',null,null,null)
on conflict (brand) do update set
  category = coalesce(excluded.category, public.brands.category),
  sales_poc = coalesce(excluded.sales_poc, public.brands.sales_poc),
  onboarding_poc = coalesce(excluded.onboarding_poc, public.brands.onboarding_poc);

-- Rebuild paid/onboarded routing master from brands that have a KC Sales POC.
insert into public.paid_brands (brand, spoc, category, active) values
('3Dclay-Art Station By Riya Patel','Renu','Decor',true),
('Action Tesa','Roshan','Wood',true),
('Adhvik Décor','Garima','Furnishing',true),
('Aflux India Lighting Expert Since 2009','Roshan','Electrical',true),
('AGL Tiles World','Kanishk','Tile',true),
('Aica','Roshan','Wood',true),
('Alex','Renu','ACP',true),
('Artline Creation(Vikas Enterprises)','Rahul','Decor',true),
('Artociti Canvas Private Limited','Suhana','Decor-Wall Art & Wall Painting',true),
('Atcraft Creations Private Limited','Renu','Hardware',true),
('Athmer','Soham','Hardware (Sealants)',true),
('Aurelia Knots','Garima','Decor',true),
('Beton Gold','Soham','Wood',true),
('Bilawat Marbles','Kanishk','Stone',true),
('Black Cobra','Renu','polymercomposite panels louvers jali and screens wpc board ply and board laminates',true),
('Blue Knot Home Pvt Ltd','Vaishali','Carpet',true),
('Bodaq','Renu','Interior Finishes (Film)',true),
('Casagres Tile (Motto)','Simran Pandita','Tiles',true),
('Century','Dhiraj','Wood',true),
('CrossBond','Roshan','Wood',true),
('CrudeFree','Harsh','Eco-friendly Surfaces / Finishes',true),
('DEE PEARLS','Renu','Stone',true),
('Door Base','Shiv','Hardware',true),
('DRV Overseas Export','Roshan','Wood',true),
('Duro','Renu','Wood',true),
('Elegancia','Kanishk','Furnishing / Wallpaper',true),
('Everite Agencies Pvt Ltd','Nikhil','Hardware',true),
('Fensa Window','Shiv','Doors & Windows',true),
('Frits Jurgen','Soham','Hardware (Hinges)',true),
('Glamstone','Renu','Stone',true),
('Gold Plus Float Glass','Roshan','Glass',true),
('Greenlam','Roshan','Wood(Laminate)',true),
('Haique Esprit Stone Limited','Ayush','Stone',true),
('Handlier','Renu','Hardware',true),
('Incor','Renu','Doors & Windows',true),
('Indian Granite','Shiv','Stone',true),
('Karnav','Renu','Wood(Veneer)',true),
('Kei Industries','Kanishk','Electrical - Wires & Cables',true),
('Kohinoor Woollen Carpet','Astha','Carpets',true),
('Kopek Kitchens','Kanishk','Modular Kitchens / Furniture',true),
('Livin Blinds','Shiv','Blinds',true),
('Luxture surface Coating Pvt Ltd','Kanishk','Paint & Coats',true),
('Madhusudan Marble Pvt Ltd','Ayush','Stone',true),
('Mark Decor','Pratibha','Polymer Composite',true),
('Metro Arte Ceramica','Simran Pandita','Tiles',true),
('NewMika','Roshan','Wood(Laminate)',true),
('Mkasa Decor(Wooden Louver)','Roshan','Louvers',true),
('Moldo Sports, Bizzar','Renu','All',true),
('Norisys Technology Private Limited','Pihu','Electrical - Switches & Sockets',true),
('Nuzen','Roshan','Home Appliances',true),
('Oasis','Renu','Hardware',true),
('P.K Lighting (Scoot)','Suhana','Electrical',true),
('Pavit Inspired Mind Capes','Simran pandita','Tile',true),
('Pioneer','Renu','Hardware',true),
('Prarthana Wootlex Pvt. Ltd.','Shiv','Fabric (Natural)',true),
('Response Fabrics','Renu','Furnishing',true),
('Sachi Art Design','Garima','Art & Decor',true),
('Saf India Galss','Shiv','Doors & Windows',true),
('Specta Quartz Surfaces','Shiv','Stone',true),
('Sris Ma Fils Premium Door Handles & Locks','Pihu','Hardware',true),
('Surajwood Products Pvt Ltd','Renu','Polymer Composite',true),
('The Art Super Craft','Suhana','Decor-Wall Art & Wall Painting',true),
('The Tile World','Renu','Tile(Terracota)',true),
('TOYAMA FLOORS INDIA','Soham','Wood (Flooring) & Polymer Composite',true),
('Twigs Direct','Soham','Furniture',true),
('UDC Homes','Renu','Wallpaper & Decor',true),
('Veneto Wardrobes & More','Shiv','Doors & Windows',true),
('Vetra Furnitures','Renu','Furniture',true),
('Vikram Carpets(Vikas Enterprises)','Vaishali','Carpets',true),
('Winvista','Kanishk','Doors & Windows',true),
('Wood Walk','Soham','Wood',true),
('Wudlay','Garima','Wood',true),
('Yen Door Closer','Daksh','Hardware',true),
('Amit Marbles','Ayush',null,true),
('Camrola Quartz','Soham',null,true),
('Datti Ram Marbles','Soham',null,true),
('Essgeeleather Goods','Suhana',null,true),
('JSB','Soham',null,true),
('Krishna Stonex','Soham',null,true),
('Mahayco','Soham',null,true),
('O.P. Marbles','Soham',null,true),
('RKS Marbles','Soham',null,true),
('Shubh Gem Stone','Soham',null,true),
('Square Root','Kanishk',null,true),
('Vaishno Light','Suhana',null,true),
('Vasudev','Ayush',null,true),
('Vinay Marbles','Soham',null,true),
('Square 1','Daksh','Hardware',true),
('A-Class Marble','Renu','Stone',true),
('Wonder Alu Board (G.M Alloys Private Limited)','Daksh',null,true),
('JK Stone','Soham',null,true),
('Althiacraft','Roshan',null,true),
('Tata Pravesh','Roshan',null,true),
('Aristo','Roshan',null,true),
('OTS Impex','Roshan',null,true),
('AEGON','Harsh',null,true),
('TACO','Harsh',null,true),
('Ritu bricks','Harsh',null,true),
('NCJ','Shiv',null,true),
('DORPICK','Harsh',null,true),
('Simpolo Tiles & Bathware','Renu',null,true),
('QIBO','Renu',null,true),
('Billion ply','Renu',null,true),
('Nayur Paints','Shiv',null,true),
('Modutech','Shiv',null,true)
on conflict (brand) do update set
  spoc = excluded.spoc,
  category = coalesce(excluded.category, public.paid_brands.category),
  active = true;

-- Make sure every referenced SPOC exists as a team member (for dropdowns + email routing).
insert into public.team_members (name, role) values
('Astha','Sales'),
('Ayush','Sales'),
('Daksh','Sales'),
('Dhiraj','Sales'),
('Garima','Sales'),
('Harsh','Sales'),
('Kanishk','Sales'),
('Nikhil','Sales'),
('Pihu','Sales'),
('Pratibha','Sales'),
('Rahul','Sales'),
('Renu','Sales'),
('Roshan','Sales'),
('Shiv','Sales'),
('Simran Pandita','Sales'),
('Simran pandita','Sales'),
('Soham','Sales'),
('Suhana','Sales'),
('Vaishali','Sales')
on conflict (name) do nothing;
