-- KC PROJECT LEADS — migration 0008: Category Master + lead scoring & split
-- Loads the INSITE Category Master (Domain -> Group -> Family) and switches routing
-- to the 11 real Domains. Adds classification, scoring attributes, and a self-link
-- so one lead can be split into multiple material leads.
-- Run AFTER 0001-0007. Idempotent.

-- ---- Category Master (reference taxonomy) ----
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  domain text not null,
  category_group text not null,
  family text not null,
  active boolean default true,
  unique (domain, category_group, family)
);
alter table public.categories enable row level security;
drop policy if exists "anon_all" on public.categories;
create policy "anon_all" on public.categories for all to anon, authenticated using (true) with check (true);
grant all on public.categories to anon, authenticated;

insert into public.categories (domain, category_group, family) values
('Building Envelope','Doors & Windows','Curtain Wall & Facade Systems'),
('Building Envelope','Doors & Windows','Door Hardware & Fittings'),
('Building Envelope','Doors & Windows','Doors'),
('Building Envelope','Doors & Windows','Garage & Industrial Doors'),
('Building Envelope','Doors & Windows','Insect Screens'),
('Building Envelope','Doors & Windows','Louvres & Vents'),
('Building Envelope','Doors & Windows','Shading & Solar Control'),
('Building Envelope','Doors & Windows','Skylight & Roof Glazing'),
('Building Envelope','Doors & Windows','Window Systems & Frames'),
('Building Envelope','Roofing & Waterproofing','Adhesives'),
('Building Envelope','Roofing & Waterproofing','Roofing Systems'),
('Building Envelope','Roofing & Waterproofing','Sealants'),
('Building Envelope','Roofing & Waterproofing','Tapes'),
('Building Envelope','Roofing & Waterproofing','Waterproofing'),
('Building Materials','Aluminium & Decorative Metals','Aluminium Profiles & Extrusions'),
('Building Materials','Building Materials — General','Brick & Block Masonry'),
('Building Materials','Building Materials — General','Concrete Repair'),
('Building Materials','Building Materials — General','Conservation Materials'),
('Building Materials','Building Materials — General','Corrosion Protection'),
('Building Materials','Building Materials — General','Fiber Cement & Calcium Silicate'),
('Building Materials','Building Materials — General','Glass'),
('Building Materials','Building Materials — General','Insulation'),
('Building Materials','Building Materials — General','Masonry Stone'),
('Building Materials','Building Materials — General','Plasterboard (Gypsum)'),
('Building Materials','Building Materials — General','Precast Concrete Products'),
('Building Materials','Building Materials — General','Prefabricated Construction'),
('Building Materials','Building Materials — General','Retaining Walls & Earth Structures'),
('Building Materials','Building Materials — General','Seismic & Vibration Control'),
('Building Materials','Cork & Leather','Cork Products'),
('Building Materials','Cork & Leather','Leather Finishes'),
('Building Materials','Decorative Metals & Metalwork','Brass & Bronze Products'),
('Building Materials','Decorative Metals & Metalwork','Copper & Copper Alloys'),
('Building Materials','Decorative Metals & Metalwork','Metal Mesh & Decorative Screens'),
('Building Materials','Decorative Metals & Metalwork','Stainless Steel Specialties'),
('Building Materials','Natural Stone, Marble & Granite','Granite & Quartz Surfaces'),
('Building Materials','Natural Stone, Marble & Granite','Marble & Travertine'),
('Building Materials','Natural Stone, Marble & Granite','Mosaic & Inlay Work'),
('Building Materials','Natural Stone, Marble & Granite','Onyx & Semi-Precious Stone'),
('Building Materials','Natural Stone, Marble & Granite','Sandstone & Limestone'),
('Building Materials','Natural Stone, Marble & Granite','Slate & Natural Stone Tiles'),
('Building Materials','Natural Stone, Marble & Granite','Terrazzo & Composite Stone'),
('Building Materials','Plastics & Polymers','Carbon Fiber & Advanced Composites'),
('Building Materials','Plastics & Polymers','Epoxy & Resin Systems'),
('Building Materials','Plastics & Polymers','Fiberglass & GRP Composites'),
('Building Materials','Plastics & Polymers','Foam & Cellular Materials'),
('Building Materials','Plastics & Polymers','Plastic & Polymer Sheets'),
('Building Materials','Plastics & Polymers','Polycarbonate & Acrylic Glazing'),
('Building Materials','Plastics & Polymers','Polyurethane Products'),
('Building Materials','Plastics & Polymers','PVC Profiles & Products'),
('Building Materials','Plastics & Polymers','Rubber & Elastomers'),
('Building Materials','Plastics & Polymers','Silicone Products'),
('Building Materials','Wood & Timber','Bamboo & Natural Fiber Construction'),
('Building Materials','Wood & Timber','Engineered Wood & Board'),
('Building Materials','Wood & Timber','Timber & Wood'),
('Energy & Sustainability','Energy & Sustainability','Battery & Energy Storage'),
('Energy & Sustainability','Energy & Sustainability','EV Charging Infrastructure'),
('Energy & Sustainability','Energy & Sustainability','Geothermal & Heat Exchange'),
('Energy & Sustainability','Energy & Sustainability','Solar Energy & Photovoltaic Systems'),
('Energy & Sustainability','Energy & Sustainability','Sustainable & Eco Materials'),
('Energy & Sustainability','Energy & Sustainability','Thermal Energy Systems'),
('Energy & Sustainability','Energy & Sustainability','Wind Energy Components'),
('Furniture & Interiors','Bedding & Linen','Bathroom Linen & Towels'),
('Furniture & Interiors','Bedding & Linen','Bedding & Bed Linen'),
('Furniture & Interiors','Bedding & Linen','Table Linen & Accessories'),
('Furniture & Interiors','Carpets & Rugs','Carpet & Rugs'),
('Furniture & Interiors','Curtains, Blinds & Soft Furnishings','Blinds & Shades'),
('Furniture & Interiors','Curtains, Blinds & Soft Furnishings','Curtains & Drapery'),
('Furniture & Interiors','Decor & Accessories','Antique & Vintage Decor'),
('Furniture & Interiors','Decor & Accessories','Aquarium & Terrarium Design'),
('Furniture & Interiors','Decor & Accessories','Art & Sculpture'),
('Furniture & Interiors','Decor & Accessories','Candles, Holders & Lanterns'),
('Furniture & Interiors','Decor & Accessories','Clocks & Timepieces'),
('Furniture & Interiors','Decor & Accessories','Cultural & Religious Decor'),
('Furniture & Interiors','Decor & Accessories','Display Cases'),
('Furniture & Interiors','Decor & Accessories','Feng Shui & Vastu'),
('Furniture & Interiors','Decor & Accessories','Florals & Botanicals'),
('Furniture & Interiors','Decor & Accessories','Fragrance & Aroma'),
('Furniture & Interiors','Decor & Accessories','Kids Room Decor'),
('Furniture & Interiors','Decor & Accessories','Luxury & High-End Decor'),
('Furniture & Interiors','Decor & Accessories','Mirrors & Reflective Decor'),
('Furniture & Interiors','Decor & Accessories','Pet-Friendly Decor'),
('Furniture & Interiors','Decor & Accessories','Photo Frames & Wall Art Displays'),
('Furniture & Interiors','Decor & Accessories','Seasonal & Event Decor'),
('Furniture & Interiors','Decor & Accessories','Theme & Style Decor'),
('Furniture & Interiors','Decor & Accessories','Tribal & Artisanal Craft'),
('Furniture & Interiors','Decor & Accessories','Trophies & Awards'),
('Furniture & Interiors','Decor & Accessories','Vases, Planters & Pottery'),
('Furniture & Interiors','Fabrics & Textiles','Fabric & Textiles'),
('Furniture & Interiors','Furniture','Display & Retail Systems'),
('Furniture & Interiors','Furniture','Furniture'),
('Furniture & Interiors','Furniture','Home Office & Study Furniture'),
('Furniture & Interiors','Furniture','Outdoor Furniture & Seating'),
('Furniture & Interiors','Furniture','Shelving & Display Units'),
('Furniture & Interiors','Furniture','Storage & Organisation'),
('Furniture & Interiors','Furniture','Wardrobe & Closet Systems'),
('Furniture & Interiors','Specialty Rooms & Wellness','Gaming & Entertainment Rooms'),
('Furniture & Interiors','Specialty Rooms & Wellness','Gym & Fitness Room Design'),
('Furniture & Interiors','Specialty Rooms & Wellness','Home Theater & Media Rooms'),
('Furniture & Interiors','Specialty Rooms & Wellness','Library & Reading Room'),
('Furniture & Interiors','Specialty Rooms & Wellness','Meditation & Yoga Spaces'),
('Furniture & Interiors','Specialty Rooms & Wellness','Sauna, Steam & Wellness Rooms'),
('Furniture & Interiors','Specialty Rooms & Wellness','Wine Cellar & Bar Design'),
('Furniture & Interiors','Upholstery & Cushions','Cushions, Throws & Pillows'),
('Furniture & Interiors','Upholstery & Cushions','Upholstery & Soft Furnishings'),
('Hardware, Tools & Services','Cleaning & Maintenance','Cleaning & Maintenance Products'),
('Hardware, Tools & Services','Cleaning & Maintenance','Laundry Room Solutions'),
('Hardware, Tools & Services','Hardware & Ironmongery','Decorative Hardware'),
('Hardware, Tools & Services','Hardware & Ironmongery','Signage & Wayfinding'),
('Hardware, Tools & Services','Tools & Equipment','Construction Consumables & Accessories'),
('Hardware, Tools & Services','Tools & Equipment','Electrical Tools & Accessories'),
('Hardware, Tools & Services','Tools & Equipment','Gardening Tools'),
('Hardware, Tools & Services','Tools & Equipment','Hand Tools'),
('Hardware, Tools & Services','Tools & Equipment','Landscaping Tools'),
('Hardware, Tools & Services','Tools & Equipment','Measuring Instruments'),
('Hardware, Tools & Services','Tools & Equipment','Painting Tools & Accessories'),
('Hardware, Tools & Services','Tools & Equipment','Plumbing Tools & Accessories'),
('Hardware, Tools & Services','Tools & Equipment','Power Tools & Equipment'),
('Hardware, Tools & Services','Tools & Equipment','Rigging, Lifting & Material Handling'),
('Hardware, Tools & Services','Tools & Equipment','Testing Instruments'),
('Hardware, Tools & Services','Tools & Equipment','Tiling & Masonry Tools'),
('Hardware, Tools & Services','Tools & Equipment','Woodworking Tools'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Acoustic Materials'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Ceiling Systems'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Ceramic & Porcelain Tiles'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Flooring'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Laminates & Veneers'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Raised Access Flooring'),
('Interior Surfaces & Finishes','Flooring, Tiles & Surfaces','Wall Finishes & Cladding'),
('Interior Surfaces & Finishes','Paints & Coatings','Decorative Plaster & Stucco'),
('Interior Surfaces & Finishes','Paints & Coatings','Paint & Colour'),
('Interior Surfaces & Finishes','Paints & Coatings','Wallpaper & Wallcovering'),
('Interior Surfaces & Finishes','Paints & Coatings','Wood Finishes & Polish'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Balustrades & Railings'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Grab Bars (Accessibility)'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Handrails'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Partitions & Dividers'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Ramps & Accessible Transitions'),
('Interior Surfaces & Finishes','Staircases, Railings & Partitions','Staircases & Steps'),
('Interior Surfaces & Finishes','Wall, Ceiling & Acoustic Finishes','Acoustic Materials'),
('Interior Surfaces & Finishes','Wall, Ceiling & Acoustic Finishes','Ceiling Systems'),
('Interior Surfaces & Finishes','Wall, Ceiling & Acoustic Finishes','Drywall & Partitions'),
('Interior Surfaces & Finishes','Wall, Ceiling & Acoustic Finishes','Mouldings & Trims'),
('Interior Surfaces & Finishes','Wall, Ceiling & Acoustic Finishes','Wall Finishes & Cladding'),
('Kitchen & Bathroom','Bathroom & Sanitaryware','Bathroom & Spa Decor'),
('Kitchen & Bathroom','Bathroom & Sanitaryware','Sanitaryware & Bathroom Fittings'),
('Kitchen & Bathroom','Kitchen & Appliances','Countertops & Worktops'),
('Kitchen & Bathroom','Kitchen & Appliances','Joinery & Millwork'),
('Kitchen & Bathroom','Kitchen & Appliances','Kitchen & Home Appliances'),
('Kitchen & Bathroom','Kitchen & Appliances','Kitchen Accessories'),
('Kitchen & Bathroom','Kitchen & Appliances','Modular Kitchen Systems'),
('Kitchen & Bathroom','Kitchen & Appliances','Tableware & Dining'),
('MEP Systems','Electrical & Wiring','Electrical Systems'),
('MEP Systems','Electrical & Wiring','ELV & Security Systems'),
('MEP Systems','ELV, Lighting & Smart Systems','Audio Visual (AV) Systems'),
('MEP Systems','ELV, Lighting & Smart Systems','Smart Home & Building Automation'),
('MEP Systems','HVAC & Ventilation','Air Grilles, Registers & Diffusers'),
('MEP Systems','HVAC & Ventilation','Elevators & Escalators'),
('MEP Systems','HVAC & Ventilation','HVAC Systems'),
('MEP Systems','HVAC & Ventilation','Indoor Air Quality (IAQ)'),
('MEP Systems','Lighting','Daylighting & Light Tubes'),
('MEP Systems','Lighting','Lighting'),
('MEP Systems','Lighting','Lighting Controls & Automation'),
('MEP Systems','Plumbing & Water Systems','Drainage & Manhole Systems'),
('MEP Systems','Plumbing & Water Systems','Gutters & Rainwater Systems'),
('MEP Systems','Plumbing & Water Systems','Pipes & Fittings'),
('MEP Systems','Plumbing & Water Systems','Pumps'),
('MEP Systems','Plumbing & Water Systems','Water Tanks'),
('MEP Systems','Plumbing & Water Systems','Water Treatment'),
('Outdoor & Landscape','Outdoor & Landscape','Decking & Boardwalk Systems'),
('Outdoor & Landscape','Outdoor & Landscape','Fencing & Gate Systems'),
('Outdoor & Landscape','Outdoor & Landscape','Garden Structures'),
('Outdoor & Landscape','Outdoor & Landscape','Green Roof Systems'),
('Outdoor & Landscape','Outdoor & Landscape','Landscape & Biophilic Design'),
('Outdoor & Landscape','Outdoor & Landscape','Living Wall Systems'),
('Outdoor & Landscape','Outdoor & Landscape','Outdoor Kitchen'),
('Outdoor & Landscape','Outdoor & Landscape','Outdoor Living & Patio'),
('Outdoor & Landscape','Outdoor & Landscape','Paving & Hardscape'),
('Outdoor & Landscape','Outdoor & Landscape','Pergolas & Gazebos'),
('Outdoor & Landscape','Outdoor & Landscape','Playground & Recreation Equipment'),
('Outdoor & Landscape','Outdoor & Landscape','Sports Surfaces'),
('Outdoor & Landscape','Outdoor & Landscape','Swimming Pools'),
('Outdoor & Landscape','Outdoor & Landscape','Water Features'),
('Safety & Compliance','Safety & Fire Protection','Child Safety Materials'),
('Safety & Compliance','Safety & Fire Protection','Elderly & Accessibility'),
('Safety & Compliance','Safety & Fire Protection','Emergency & Exit Lighting'),
('Safety & Compliance','Safety & Fire Protection','Fire Detection & Alarm'),
('Safety & Compliance','Safety & Fire Protection','Fire Protection & Safety'),
('Safety & Compliance','Safety & Fire Protection','Fire Suppression Systems'),
('Safety & Compliance','Safety & Fire Protection','Fireproofing & Intumescent Coatings'),
('Safety & Compliance','Safety & Fire Protection','Heat & Natural Ventilation'),
('Safety & Compliance','Safety & Fire Protection','Lightning Protection Systems'),
('Safety & Compliance','Safety & Fire Protection','Sensory Room Materials'),
('Safety & Compliance','Safety & Fire Protection','Smoke Ventilation (SHEV)'),
('Safety & Compliance','Site Safety & PPE','Site Safety & PPE'),
('Structure & Civil Works','Concrete & Cement','Concrete & Cement'),
('Structure & Civil Works','Concrete & Cement','Mortar & Grout'),
('Structure & Civil Works','Steel & Structural Metals','Steel & Metals')
on conflict (domain, category_group, family) do nothing;

-- ---- Domain -> Category Team Lead mapping (11 real domains) ----
-- Remove the old ad-hoc 6-domain lead rows, then set the confirmed mapping.
delete from public.app_settings where key like 'lead:%';
insert into public.app_settings (key, value, note) values
('lead:'||'Building Envelope','Roshan', 'Category Team Lead for '||'Building Envelope'),
('lead:'||'Building Materials','Renu', 'Category Team Lead for '||'Building Materials'),
('lead:'||'Energy & Sustainability','', 'Category Team Lead for '||'Energy & Sustainability'),
('lead:'||'Furniture & Interiors','', 'Category Team Lead for '||'Furniture & Interiors'),
('lead:'||'Hardware, Tools & Services','Harsh', 'Category Team Lead for '||'Hardware, Tools & Services'),
('lead:'||'Interior Surfaces & Finishes','Renu', 'Category Team Lead for '||'Interior Surfaces & Finishes'),
('lead:'||'Kitchen & Bathroom','', 'Category Team Lead for '||'Kitchen & Bathroom'),
('lead:'||'MEP Systems','Rutvij', 'Category Team Lead for '||'MEP Systems'),
('lead:'||'Outdoor & Landscape','', 'Category Team Lead for '||'Outdoor & Landscape'),
('lead:'||'Safety & Compliance','', 'Category Team Lead for '||'Safety & Compliance'),
('lead:'||'Structure & Civil Works','', 'Category Team Lead for '||'Structure & Civil Works')
on conflict (key) do update set value = excluded.value, note = excluded.note;

-- ---- Lead classification + scoring + split columns ----
alter table public.lead_register add column if not exists domain text;
alter table public.lead_register add column if not exists category_group text;
alter table public.lead_register add column if not exists category_family text;
alter table public.lead_register add column if not exists quantity text;
alter table public.lead_register add column if not exists unit text;
alter table public.lead_register add column if not exists specification text;   -- grade / shade / thickness / spec
alter table public.lead_register add column if not exists application text;
alter table public.lead_register add column if not exists project_type text;
alter table public.lead_register add column if not exists project_scale text;
alter table public.lead_register add column if not exists project_location text;
alter table public.lead_register add column if not exists target_price text;
alter table public.lead_register add column if not exists sample_required text;   -- Yes / No / Unknown
alter table public.lead_register add column if not exists special_requirements text; -- Fire Rated, Water Resistant, Warranty, Termite, Design Certificate...
alter table public.lead_register add column if not exists lead_score int;
alter table public.lead_register add column if not exists parent_lead_id uuid;     -- set on component leads from a split

-- brand opportunities carry the same classification for the sanitized email
alter table public.brand_opportunities add column if not exists category_group text;
alter table public.brand_opportunities add column if not exists category_family text;

create index if not exists idx_lr_domain on public.lead_register(domain);
create index if not exists idx_lr_parent on public.lead_register(parent_lead_id);
